package bl

var COLOR_SOLID, COLOR_HORIZ_GRADIENT, COLOR_VERT_GRADIENT uint32
var OPACITY_SOLID, OPACITY_HORIZ_GRADIENT, OPACITY_VERT_GRADIENT uint32
var LABEL_ALIGN_LEFT, LABEL_ALIGN_TOP, LABEL_ALIGN_RIGHT, LABEL_ALIGN_BOTTOM, LABEL_ALIGN_VCENTER, LABEL_ALIGN_HCENTER uint32
var BORDER_LEFT, BORDER_TOP, BORDER_RIGHT, BORDER_BOTTOM uint32

var BORDER_ALL, BORDER_ANY uint32

func init() {
	COLOR_SOLID = 1 << 0
	COLOR_HORIZ_GRADIENT = 1 << 1
	COLOR_VERT_GRADIENT = 1 << 2

	OPACITY_SOLID = 1 << 3
	OPACITY_HORIZ_GRADIENT = 1 << 4
	OPACITY_VERT_GRADIENT = 1 << 5

	LABEL_ALIGN_LEFT = 1 << 6
	LABEL_ALIGN_TOP = 1 << 7
	LABEL_ALIGN_RIGHT = 1 << 8
	LABEL_ALIGN_BOTTOM = 1 << 9
	LABEL_ALIGN_VCENTER = 1 << 10
	LABEL_ALIGN_HCENTER = 1 << 11

	BORDER_LEFT = 1 << 12
	BORDER_TOP = 1 << 13
	BORDER_RIGHT = 1 << 14
	BORDER_BOTTOM = 1 << 15

	BORDER_ALL = BORDER_LEFT | BORDER_TOP | BORDER_RIGHT | BORDER_BOTTOM
	BORDER_ANY = BORDER_ALL
}
