package bl

var Z_COLOR_SOLID, Z_COLOR_HORIZ_GRADIENT, Z_COLOR_VERT_GRADIENT uint32
var Z_OPACITY_SOLID, Z_OPACITY_HORIZ_GRADIENT, Z_OPACITY_VERT_GRADIENT uint32
var Z_LABEL_ALIGN_LEFT, Z_LABEL_ALIGN_TOP, Z_LABEL_ALIGN_RIGHT, Z_LABEL_ALIGN_BOTTOM, Z_LABEL_ALIGN_VCENTER, Z_LABEL_ALIGN_HCENTER uint32
var Z_BORDER_LEFT, Z_BORDER_TOP, Z_BORDER_RIGHT, Z_BORDER_BOTTOM uint32

var Z_BORDER_ALL, Z_BORDER_ANY uint32

func init() {
	Z_COLOR_SOLID = 1 << 0
	Z_COLOR_HORIZ_GRADIENT = 1 << 1
	Z_COLOR_VERT_GRADIENT = 1 << 2

	Z_OPACITY_SOLID = 1 << 3
	Z_OPACITY_HORIZ_GRADIENT = 1 << 4
	Z_OPACITY_VERT_GRADIENT = 1 << 5

	Z_LABEL_ALIGN_LEFT = 1 << 6
	Z_LABEL_ALIGN_TOP = 1 << 7
	Z_LABEL_ALIGN_RIGHT = 1 << 8
	Z_LABEL_ALIGN_BOTTOM = 1 << 9
	Z_LABEL_ALIGN_VCENTER = 1 << 10
	Z_LABEL_ALIGN_HCENTER = 1 << 11

	Z_BORDER_LEFT = 1 << 12
	Z_BORDER_TOP = 1 << 13
	Z_BORDER_RIGHT = 1 << 14
	Z_BORDER_BOTTOM = 1 << 15

	Z_BORDER_ALL = Z_BORDER_LEFT | Z_BORDER_TOP | Z_BORDER_RIGHT | Z_BORDER_BOTTOM
	Z_BORDER_ANY = Z_BORDER_ALL
}
