package bl

var flag_COLOR_SOLID, flag_SKIP_NODE_RECT_DRAW, flag_COLOR_HORIflag_GRADIENT, flag_COLOR_VERT_GRADIENT uint32
var flag_OPACITY_SOLID, flag_OPACITY_HORIflag_GRADIENT, flag_OPACITY_VERT_GRADIENT uint32
var flag_LABEL_ALIGN_LEFT, flag_LABEL_ALIGN_TOP, flag_LABEL_ALIGN_RIGHT, flag_LABEL_ALIGN_BOTTOM, flag_LABEL_ALIGN_VCENTER, flag_LABEL_ALIGN_HCENTER uint32
var flag_BORDER_LEFT, flag_BORDER_TOP, flag_BORDER_RIGHT, flag_BORDER_BOTTOM uint32

var flag_BORDER_ALL, flag_BORDER_ANY uint32

func init() {
	flag_COLOR_SOLID = 1 << 0
	flag_COLOR_HORIflag_GRADIENT = 1 << 1
	flag_COLOR_VERT_GRADIENT = 1 << 2

	flag_OPACITY_SOLID = 1 << 3
	flag_OPACITY_HORIflag_GRADIENT = 1 << 4
	flag_OPACITY_VERT_GRADIENT = 1 << 5

	flag_LABEL_ALIGN_LEFT = 1 << 6
	flag_LABEL_ALIGN_TOP = 1 << 7
	flag_LABEL_ALIGN_RIGHT = 1 << 8
	flag_LABEL_ALIGN_BOTTOM = 1 << 9
	flag_LABEL_ALIGN_VCENTER = 1 << 10
	flag_LABEL_ALIGN_HCENTER = 1 << 11

	flag_BORDER_LEFT = 1 << 12
	flag_BORDER_TOP = 1 << 13
	flag_BORDER_RIGHT = 1 << 14
	flag_BORDER_BOTTOM = 1 << 15

	flag_SKIP_NODE_RECT_DRAW = 1 << 16

	flag_BORDER_ALL = flag_BORDER_LEFT | flag_BORDER_TOP | flag_BORDER_RIGHT | flag_BORDER_BOTTOM
	flag_BORDER_ANY = flag_BORDER_ALL
}
